Fix tests in Python3.
ERROR: test_base (sugardough.base.tests.HomeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/sugardough/base/tests.py", line 9, in test_base
    assert 'csrfmiddlewaretoken' in response.content
TypeError: 'str' does not support the buffer interface